# MAT 345 Logistic Regression
#### Joanna Li

## 1) Linear regression

In [1]:
# import all needed libraries
import pandas as pd
import numpy as np
import math

In [2]:
trainingSet = pd.read_excel('Project3.xlsx', sheet_name='Training')

In [3]:
x = np.c_[trainingSet.iloc[:, :3]]
y = np.c_[trainingSet.loc[:, 'Course Grade']]

In [4]:
# augment x 
xAug = np.concatenate(((np.ones(x.shape[0]))[:, np.newaxis], x), axis=1)

In [5]:
# find x ^ T * X
xTranX = np.matmul(xAug.T, xAug)

# find x^T * y
xTranY = np.matmul(xAug.T, y)

# find (x^T * x) ^-1
xTranXInverse =  np.linalg.inv(xTranX)

In [6]:
weight = np.matmul(xTranXInverse, xTranY)

### Final Weight

In [7]:
print(weight)

[[7.66712306]
 [0.31262773]
 [0.15289359]
 [0.43866389]]


In [8]:
testingSet = pd.read_excel('Project3.xlsx', sheet_name='Predict')

In [9]:
xMat = np.c_[testingSet]

In [10]:
# augment matrix
xMat = np.concatenate(((np.ones(xMat.shape[0]))[:, np.newaxis], xMat), axis=1)

In [11]:
# predict course grade with weight found
courseGrade = np.dot(weight.T, xMat.T).T

In [12]:
testingSet['Course Grade Predicted'] = courseGrade

In [13]:
testingSet

Midterm  Homework  Quiz  Course Grade Predicted
0        49        79    71               66.209611
1        56        21    46               48.563580
2        58       100    79               75.743337
3        61        82    58               64.717194
4        62        90    62               68.007626
5        66        99    75               76.336810
6        71        73    65               69.538076
7        73        87    80               78.883800
8        73        97    73               77.342089
9        74        73    77               75.739926
10       74        85    66               72.749346
11       74       100    87               84.254692
12       78        79    56               68.695857
13       80        72    71               74.830815
14       80        82    90               84.694365
15       81        56    60               67.871843
16       81        80    78               79.437239
17       82       100    79               83.246402
18       83        80    56               70.411889
19       83        96    64               76.367498
20       84        98    85               86.197854
21       84       100    77               82.994330
22       85        93    75               81.359375
23       85        99    69               79.644753
24       86        95    77               82.855118
25       86       100    85               87.128897
26       87        97    75               82.596205
27       87        98    89               88.890393
28       87        99    85               87.288631
29       87        99    90               89.481950
30       87        99    81               85.533975
31       88        99    73               82.337292
32       89        82    37               64.258829
33       89        82    81               83.560040
34       89        99    64               78.701945
35       89        99    79               85.281903
36       90       100    90               90.572727
37       91        67    84               83.207883
38       91       100    79               86.060052
39       92        99    85               88.851769
40       93        97    71               82.717316
41       94        99    89               91.231680
42       95        98    85               89.636759
43       95        99    69               82.771030
44       97        80    79               84.877947
45       97        97    85               90.109121
46       97        99    92               93.485555
47       97       100    87               91.445129
48       98       100    81               89.125774
49       99       100   100               97.773015
50      100        76    90               90.029558
51      100        94    94               94.536298
52      100       100    94               95.453660
53      100       100    92               94.576332

### 2) Read in training set and modify output to denote fail or pass (Logisitic Regression Part)

In [14]:
# read in training set
trainingSet = pd.read_excel('Project3.xlsx', sheet_name='Training')

In [15]:
# Modify output to denote fail or pass, less than 70 = fail else pass
trainingSet['Course Grade'] = pd.cut(trainingSet['Course Grade'], bins=[0, 69, 100], labels=[-1, 1])

In [16]:
trainingSet

Midterm  Homework  Quiz Course Grade
0         56        25    24           -1
1         40        16    24           -1
2         64        27    19           -1
3         50        30    29           -1
4         73        39    32           -1
..       ...       ...   ...          ...
326       98        99   100            1
327      100        99    93            1
328       95       100   100            1
329       98        97   100            1
330       96        94   100            1

[331 rows x 4 columns]

In [17]:
#everything except last column
xTrain = trainingSet.iloc[:, :-1]
xTrain = np.c_[xTrain]

In [18]:
xTrain

array([[ 56,  25,  24],
       [ 40,  16,  24],
       [ 64,  27,  19],
       [ 50,  30,  29],
       [ 73,  39,  32],
       [ 65,  46,  58],
       [ 76,  85,  41],
       [ 75,  53,  36],
       [ 92,  37,  74],
       [ 48,  96,  39],
       [ 37,  23,  41],
       [ 59,  66,  51],
       [ 44,  93,  46],
       [ 56,  35,  60],
       [ 74,  53,  59],
       [ 52,  90,  49],
       [ 60,  27,  61],
       [ 58,  28,  46],
       [ 79,  64,  60],
       [ 74,  47,  50],
       [ 86,  85,  68],
       [ 72,  46,  63],
       [ 69, 100,  49],
       [ 79,  26,  58],
       [ 61,  56,  36],
       [ 73,  36,  70],
       [ 51,  52,  50],
       [ 62,  74,  58],
       [ 58,  73,  61],
       [ 67,  64,  63],
       [ 72,  71,  72],
       [ 61,  69,  58],
       [ 62,  91,  62],
       [ 81,  27,  70],
       [ 73,  30,  63],
       [ 69,  48,  70],
       [ 69,  43,  58],
       [ 57,  97,  53],
       [ 57,  76,  59],
       [ 82,   9,  44],
       [ 60,  66,  90],
       [ 78,  64

In [19]:
yTrain = np.array(trainingSet.iloc[:, -1])

In [20]:
yTrain

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

### 3) Run Logistic Regression Algorithm with Gradient Descent

In [21]:
class LogisticRegression:
    def __init__(self, x, y, learningRate, iterations):
        self.x = x
        self.y = y
        self.w = None
        self.lr = learningRate
        self.steps = iterations
        
    # initalize weights to zero
    def initialize_weights(self, dim):
        self.w = np.zeros((len(dim)), dtype = float)
        
    def sigmoid(self, z):
        sig = 1/(1+np.exp(-z))
        return sig
    
    # gradient calculation
    def gradient(self, x, y):
        z = np.dot(self.w, x)
        grad = -x * y*(1- self.sigmoid(z))
        return grad
    
    # logistic regression with gradient descent
    def fit(self):        
        for i in range(self.steps):
            grad = 0
            for idx in range(len(self.x)):
                grad += self.gradient(self.x[idx], self.y[idx])

            # update weight
            self.w = self.w - self.lr * grad/len(self.x)

    def probability(self, X, w):
        z =  np.dot(w, X.T)
        predict = []
        for i in range(len(z)):
            sig = 0
            if z[i] <= 70:
                sig = self.sigmoid(-z[i])
            else:
                sig = self.sigmoid(z[i])
                
            if sig < 0.5:
                predict.append(0)
            else:
                predict.append(sig)
                
        return pd.DataFrame(predict, columns={'Probability of Passing'})

In [22]:
regressor = LogisticRegression(xTrain, yTrain, 0.01, 5000)
regressor.initialize_weights(xTrain[0])

In [23]:
regressor.fit()

### Final Weight

In [24]:
print(regressor.w)

[0.29693353 0.31549849 0.3105287 ]


## 4) Use weights found to calculate probability of passing course in the Predict set

In [25]:
# grab the predict
testingSet = pd.read_excel('Project3.xlsx', sheet_name='Predict')
pred = np.c_[testingSet]

In [26]:
pred

array([[ 49,  79,  71],
       [ 56,  21,  46],
       [ 58, 100,  79],
       [ 61,  82,  58],
       [ 62,  90,  62],
       [ 66,  99,  75],
       [ 71,  73,  65],
       [ 73,  87,  80],
       [ 73,  97,  73],
       [ 74,  73,  77],
       [ 74,  85,  66],
       [ 74, 100,  87],
       [ 78,  79,  56],
       [ 80,  72,  71],
       [ 80,  82,  90],
       [ 81,  56,  60],
       [ 81,  80,  78],
       [ 82, 100,  79],
       [ 83,  80,  56],
       [ 83,  96,  64],
       [ 84,  98,  85],
       [ 84, 100,  77],
       [ 85,  93,  75],
       [ 85,  99,  69],
       [ 86,  95,  77],
       [ 86, 100,  85],
       [ 87,  97,  75],
       [ 87,  98,  89],
       [ 87,  99,  85],
       [ 87,  99,  90],
       [ 87,  99,  81],
       [ 88,  99,  73],
       [ 89,  82,  37],
       [ 89,  82,  81],
       [ 89,  99,  64],
       [ 89,  99,  79],
       [ 90, 100,  90],
       [ 91,  67,  84],
       [ 91, 100,  79],
       [ 92,  99,  85],
       [ 93,  97,  71],
       [ 94,  99

In [27]:
# calculate probability
prob = regressor.probability(pred, regressor.w)

In [28]:
# merge the 2 dataframes
result = pd.concat([testingSet, prob], axis = 1)

In [29]:
result

Midterm  Homework  Quiz  Probability of Passing
0        49        79    71                     0.0
1        56        21    46                     0.0
2        58       100    79                     1.0
3        61        82    58                     0.0
4        62        90    62                     0.0
5        66        99    75                     1.0
6        71        73    65                     0.0
7        73        87    80                     1.0
8        73        97    73                     1.0
9        74        73    77                     0.0
10       74        85    66                     0.0
11       74       100    87                     1.0
12       78        79    56                     0.0
13       80        72    71                     0.0
14       80        82    90                     1.0
15       81        56    60                     0.0
16       81        80    78                     1.0
17       82       100    79                     1.0
18       83        80    56                     0.0
19       83        96    64                     1.0
20       84        98    85                     1.0
21       84       100    77                     1.0
22       85        93    75                     1.0
23       85        99    69                     1.0
24       86        95    77                     1.0
25       86       100    85                     1.0
26       87        97    75                     1.0
27       87        98    89                     1.0
28       87        99    85                     1.0
29       87        99    90                     1.0
30       87        99    81                     1.0
31       88        99    73                     1.0
32       89        82    37                     0.0
33       89        82    81                     1.0
34       89        99    64                     1.0
35       89        99    79                     1.0
36       90       100    90                     1.0
37       91        67    84                     1.0
38       91       100    79                     1.0
39       92        99    85                     1.0
40       93        97    71                     1.0
41       94        99    89                     1.0
42       95        98    85                     1.0
43       95        99    69                     1.0
44       97        80    79                     1.0
45       97        97    85                     1.0
46       97        99    92                     1.0
47       97       100    87                     1.0
48       98       100    81                     1.0
49       99       100   100                     1.0
50      100        76    90                     1.0
51      100        94    94                     1.0
52      100       100    94                     1.0
53      100       100    92                     1.0